services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: graduation_app_development
    ports:
      - "5433:5432"

  web:
    build: .
    command: bash -c "sleep 10 && rm -f /rails/tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  bundle_cache: